apiVersion: v1
kind: Service
metadata:
  name: finantrack-api-service
spec:
  selector:
    app: finantrack-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
