apiVersion: apps/v1
kind: Deployment
metadata:
  name: finantrack-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finantrack-db
  template:
    metadata:
      labels:
        app: finantrack-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: controle_de_gastos
        ports:
        - containerPort: 3306
