apiVersion: v1
kind: Service
metadata:
  name: finantrack-frontend-service
spec:
  type: NodePort
  selector:
    app: finantrack-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31156